parser:
  links:
    - "https://news.yandex.ru/koronavirus.rss"
    - "https://news.yandex.ru/computers.rss"
    - "https://news.yandex.ru/travels.rss"
  threads: 2
  timeout: 1
  key_words:
    - "коронавирус"
    - "авиация"

db:
  host: "localhost"
  port: 5432
  database: "dev"
  username: "postgres-dev"
  password: "1234"


observer:
  host: ""
  port: 9000